### ISSUE TITLE
Move line 35 to line 1:

### ISSUE THREAD

**Issue by YONGTEENFOH** [giulianopz/lfcs#3]
$echo "$(sed -n '35p' editme.txt)"+"$(sed -n '1,34p;36,38p' editme.txt)" > editme.txt

$cat editme.txt
35+1
2
3
4
5
6
...

# it appends line 35 to line 1

**Comment by giulianopz** [comment]
Fixed with commit #4a46c7ae682cb6d0e535de3be846e85134b31749
